export const CONFIG = {
  HOME: {
    RECENT_ARTICLES_COUNT: 5,
    FEATURED_ARTICLES_COUNT: 3,
    DESCRIPTION_MAX_LENGTH: 200,
    FALLBACK_DESCRIPTION_LENGTH: 100
  },
  ARTICLE: {
    RELATED_ARTICLES_COUNT: 3
  },
  HEADER: {
    HEIGHT: 70,
    SIDEBAR_WIDTH: 280,
    MOBILE_BREAKPOINT: 768
  },
  CATEGORY: {
    ARTICLES_PER_PAGE: 10
  },
  FRESHNESS: {
    STALE_MONTHS: 6,
    ARCHIVE_MONTHS: 12
  },
  SEARCH: {
    WEIGHT_TITLE: 10,
    WEIGHT_TAG: 8,
    WEIGHT_CATEGORY: 5,
    WEIGHT_DESCRIPTION: 3,
    WEIGHT_PARTIAL: 1
  },
  ARTICLES: {
    TAGS_MAX_DISPLAY: 6
  }
}

