export const CONFIG = {
  HOME: {
    RECENT_ARTICLES_COUNT: 5,
    FEATURED_ARTICLES_COUNT: 3,
    DESCRIPTION_MAX_LENGTH: 200,
    FALLBACK_DESCRIPTION_LENGTH: 100
  },
  ARTICLE: {
    RELATED_ARTICLES_COUNT: 3
  },
  HEADER: {
    HEIGHT: 70,
    SIDEBAR_WIDTH: 280,
    MOBILE_BREAKPOINT: 768
  },
  CATEGORY: {
    ARTICLES_PER_PAGE: 10
  }
}

